---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matter-server.${DOMAIN}
  namespace: home-automation
spec:
  secretName: matter-server.${DOMAIN}
  dnsNames:
    - ${HOST_MATTER_SERVER}.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
