---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matter-server
  namespace: home-automation
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://${HOST_MATTER_SERVER}.${DOMAIN}"
    gethomepage.dev/description: "Matter Server for smart home devices"
    gethomepage.dev/group: "Home Automation"
    gethomepage.dev/icon: matter.png
    #gethomepage.dev/app: "home-assistant"  # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Matter Server"
spec:
  entryPoints:
    - websecure
  tls:
    secretName: matter-server.${DOMAIN}
  routes:
    - kind: Rule
      match: Host(`${HOST_MATTER_SERVER}.${DOMAIN}`)
      middlewares:
        - name: security-header
          namespace: traefik
      services:
        - name: home-assistant
          kind: Service
          namespace: home-automation
          port: 5580
