---
resources:
  - matter-server-pvc.yaml
  - ../../../base/home-automation/matter-server
  - certificate.yaml
  - ingress-route.yaml

patches:
  - path: values.yaml
    target:
      kind: HelmRelease
