---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gatus.${DOMAIN}
  namespace: monitoring
spec:
  secretName: gatus.${DOMAIN}
  dnsNames:
    - ${HOST_GATUS}.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
