---
resources:
  - ./resources/config.yaml
  - ../../../base/monitoring/gatus
  - certificate.yaml
  - ingress-route.yaml
  - coap-service.yaml

# configMapGenerator:
#   - name: gatus-configmap
#     namespace: monitoring
#     files:
#       - config.yaml=./resources/config.yaml

patches:
  - path: values.yaml
    target:
      kind: HelmRelease
