---
resources:
  - ../../../base/monitoring/gatus
  - certificate.yaml
  - ingress-route.yaml

configMapGenerator:
  - name: gatus-configmap
    files:
      - config.yaml=./resources/config.yaml
  - namespace: monitoring

patches:
  - path: values.yaml
    target:
      kind: HelmRelease
