apiVersion: v1
kind: Service
metadata:
  name: home-assistant-coap
  namespace: home-automation
spec:
  type: LoadBalancer # or NodePort if you point Shelly to the Node IP
  selector:
    app.kubernetes.io/instance: home-assistant
  ports:
    - name: coap
      protocol: UDP
      port: 5683
      targetPort: 5683
  loadBalancerIP: 192.168.10.150