---
resources:
  - home-assistant-secret.enc.yaml
  - home-assistant-pvc.yaml
  - ../../../base/home-automation/home-assistant
  - certificate.yaml
  - ingress-route.yaml
  - ingress-route-udp.yaml

patches:
  - path: values.yaml
    target:
      kind: HelmRelease
