---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: music-assistant.${DOMAIN}
  namespace: media
spec:
  secretName: music-assistant.${DOMAIN}
  dnsNames:
    - ${HOST_MUSIC_ASSISTANT}.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
