---
# Gatus configuration
# ref: https://github.com/TwiN/gatus#configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-configmap
  namespace: monitoring
data:
  config.yaml: |
    # Gatus Configuration File
    connectivity:
      checker:
        target: 1.1.1.1:53
        interval: 1m

    metrics: true

    ui:
      title: Infrastructure Status
      header: Status
      logo: https://avatars.githubusercontent.com/u/48133805?v=4
      link: https://github.com/ghimele
      buttons:
        - name: Github
          link: https://github.com/ghimele
        - name: Homelab
          link: https://github.com/ghimele/homelab
    endpoints:
      - name: Cloudflare
        group: connectivity
        url: icmp://1.1.1.1
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
      - name: Google
        group: connectivity
        url: icmp://8.8.8.8
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
